### ISSUE TITLE
Paper index page should list title, venue, and year of all papers

### ISSUE THREAD

**Issue by swt2public** [hpi-swt2-exercise/rails-exercise-17-leonardo-huebscher-1#27]
### Scenario
Given a paper entitled 'COMPUTING MACHINERY AND INTELLIGENCE'
When a user visits the papers index page
Then the page should render

### Error
> Got ActionView::Template::Error: undefined local variable or method `author' for #<#<Class:0x000000024c7c08>:0x00000004bac148>
Did you mean?  author_url

*Estimated progress: 78% complete*

**Comment by deeps96** [comment]
Fixed by #779208cf8a3f793f6950a9b4e4c71e07aecc14b6.
